//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpticianMgr.Wpf.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ihre Brillenbestellung von Augenoptik Aigner")]
        public string SingleEmailSubjectGlassesOrder {
            get {
                return ((string)(this["SingleEmailSubjectGlassesOrder"]));
            }
            set {
                this["SingleEmailSubjectGlassesOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sehr geehrte/r Frau/Herr {0} {1}, {2} {2} Ihre Brillenbestellung ist nun abholber" +
            "eit! {2} {2} Dies ist eine automatisch versendete Nachricht, bitte antworten Sie" +
            " nicht auf diese E-Mail. {2} {2} Mit freundlichen Grüßen {2} Augenoptik Aigner")]
        public string SingleEmailTextGlassesOrder {
            get {
                return ((string)(this["SingleEmailTextGlassesOrder"]));
            }
            set {
                this["SingleEmailTextGlassesOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ihre Kontaktlinsenbestellung von Augenoptik Aigner")]
        public string SingleEMailSubjectContactLensOrder {
            get {
                return ((string)(this["SingleEMailSubjectContactLensOrder"]));
            }
            set {
                this["SingleEMailSubjectContactLensOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Sehr geehrte/r Frau/Herr {0} {1}, {2} {2} Ihre Kontaktlinsenbestellung ist nun ab" +
            "holbereit! {2} {2} Dies ist eine automatisch versendete Nachricht, bitte antwort" +
            "en Sie nicht auf diese E-Mail. {2} {2} Mit freundlichen Grüßen {2} Augenoptik Ai" +
            "gner")]
        public string SingleEmailTextContactLensOrder {
            get {
                return ((string)(this["SingleEmailTextContactLensOrder"]));
            }
            set {
                this["SingleEmailTextContactLensOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ihre Brillenbestellung ist nun abholbereit!")]
        public string SingleSMSTextGlassesOrder {
            get {
                return ((string)(this["SingleSMSTextGlassesOrder"]));
            }
            set {
                this["SingleSMSTextGlassesOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ihre Kontaktlinsenbestellung ist nun abholbereit!")]
        public string SingleSMSTextContactLensOrder {
            get {
                return ((string)(this["SingleSMSTextContactLensOrder"]));
            }
            set {
                this["SingleSMSTextContactLensOrder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OptikAigner")]
        public string SmsSenderText {
            get {
                return ((string)(this["SmsSenderText"]));
            }
            set {
                this["SmsSenderText"] = value;
            }
        }
    }
}
